# Welcome to Jekyll!

# Site Settings
title: "The West Blog"
description: >-
  West blog life tech and country - sharing thoughts on gaming, technology, 
  word puzzles, and life experiences.
url: "https://omoli822.github.io"
baseurl: ""
github_username: omoli822

# Author Information
author: Oliver


# Build settings - No theme, custom Jekyll
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Show excerpts on homepage
show_excerpts: true

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Comments using Utterances (GitHub-based comments)
comments:
  provider: utterances
  utterances:
    repo: "Omoli822/omoli822.github.io"
    issue_term: "pathname"
    theme: "github-light"

# Timezone
timezone: Australia/Perth

# Permalink structure
permalink: /:categories/:year/:month/:day/:title/

# Markdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Omoli822"
      show_date: true
      comments: true

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - README.md
